Validate inputs depending on vendor

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -3,7 +3,7 @@ name: K8S Setup
 description: Prepare kubectl for communication with a cluster
 inputs:
   vendor:
-    description: The vendor to communicate with (digitalocean, scaleway)
+    description: The vendor to communicate with (azure, digitalocean, scaleway)
     required: true
   cluster-id:
     description: Target cluster ID
@@ -39,32 +39,31 @@ inputs:
 runs:
   using: composite
   steps:
-    # Vendor: Scaleway
-    - name: Install scw tool
-      if: ${{ inputs.vendor == 'scaleway' }}
-      uses: scaleway/action-scw@v0
-      with:
-        access-key: ${{ inputs.scaleway-access-key }}
-        secret-key: ${{ inputs.scaleway-secret-key }}
-        default-organization-id: ${{ inputs.scaleway-organization-id }}
-        default-project-id: ${{ inputs.scaleway-project-id }}
-        export-config: true
-        save-config: true
-    - name: Save Scaleway kubeconfig
-      if: ${{ inputs.vendor == 'scaleway' }}
+    # Validate inputs
+    - name: Validate inputs
       shell: bash
-      run: scw k8s kubeconfig install ${{ inputs.cluster-id }} region=${{ inputs.scaleway-region }}
-
-    # Vendor: Digitalocean
-    - name: Install doctl tool
-      if: ${{ inputs.vendor == 'digitalocean' }}
-      uses: digitalocean/action-doctl@v2
-      with:
-        token: ${{ inputs.digitalocean-api-token }}
-    - name: Save DigitalOcean kubeconfig
-      if: ${{ inputs.vendor == 'digitalocean' }}
-      shell: bash
-      run: doctl k8s cluster kubeconfig save ${{ inputs.cluster-id }}
+      run: |
+        echo "Validating inputs for vendor: ${{ inputs.vendor }}"
+        case "${{ inputs.vendor }}" in
+          azure)
+            if [ -z "${{ inputs.azure-credentials }}" ]; then echo 'Missing input: azure-credentials'; exit 1; fi
+            if [ -z "${{ inputs.azure-resource-group }}" ]; then echo 'Missing input: azure-resource-group'; exit 1; fi
+            ;;
+          digitalocean)
+            if [ -z "${{ inputs.digitalocean-api-token }}" ]; then echo 'Missing input: digitalocean-api-token'; exit 1; fi
+            ;;
+          scaleway)
+            if [ -z "${{ inputs.scaleway-access-key }}" ]; then echo 'Missing input: scaleway-access-key'; exit 1; fi
+            if [ -z "${{ inputs.scaleway-organization-id }}" ]; then echo 'Missing input: scaleway-organization-id'; exit 1; fi
+            if [ -z "${{ inputs.scaleway-project-id }}" ]; then echo 'Missing input: scaleway-project-id'; exit 1; fi
+            if [ -z "${{ inputs.scaleway-region }}" ]; then echo 'Missing input: scaleway-region'; exit 1; fi
+            if [ -z "${{ inputs.scaleway-secret-key }}" ]; then echo 'Missing input: scaleway-secret-key'; exit 1; fi
+            ;;
+          *)
+            echo "Unsupported vendor '${{ inputs.vendor }}'"
+            exit 1
+            ;;
+        esac
 
     # Vendor: Azure
     - name: Set up kubelogin for non-interactive login
@@ -87,3 +86,30 @@ runs:
         cluster-name: ${{ inputs.cluster-id }}
         admin: 'false'
         use-kubelogin: 'true'
+
+    # Vendor: Digitalocean
+    - name: Install doctl tool
+      if: ${{ inputs.vendor == 'digitalocean' }}
+      uses: digitalocean/action-doctl@v2
+      with:
+        token: ${{ inputs.digitalocean-api-token }}
+    - name: Save DigitalOcean kubeconfig
+      if: ${{ inputs.vendor == 'digitalocean' }}
+      shell: bash
+      run: doctl k8s cluster kubeconfig save ${{ inputs.cluster-id }}
+
+    # Vendor: Scaleway
+    - name: Install scw tool
+      if: ${{ inputs.vendor == 'scaleway' }}
+      uses: scaleway/action-scw@v0
+      with:
+        access-key: ${{ inputs.scaleway-access-key }}
+        secret-key: ${{ inputs.scaleway-secret-key }}
+        default-organization-id: ${{ inputs.scaleway-organization-id }}
+        default-project-id: ${{ inputs.scaleway-project-id }}
+        export-config: true
+        save-config: true
+    - name: Save Scaleway kubeconfig
+      if: ${{ inputs.vendor == 'scaleway' }}
+      shell: bash
+      run: scw k8s kubeconfig install ${{ inputs.cluster-id }} region=${{ inputs.scaleway-region }}
